"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";

const base=process.env.NEXT_PUBLIC_REPORT_BASE_PATH??"";
const asset=(x:string)=>`${base}/${x}`;
const slides=[
["title","Title"],["opening","How it opened"],["run","Running order"],["takeaways","The story"],["reset","Platform reset"],["culture","Culture shift"],["turn","From critique to product"],["scale","Scale + intent"],["journey","Decision journey"],["intelligence","Pinterest Intelligence"],["assistant","Pinterest Assistant"],["pivot","The commercial pivot"],["promise","Advertiser promise"],["creators","Creators"],["searchads","Visual Search Ads"],["performance","Performance Plus"],["roadmap","Product roadmap"],["proof","How Pinterest made its case"],["sephora","Sephora"],["brands","Samsung + Levi's"],["measurement","Measurement"],["trends","Trends + holiday"]] as const;
const source="Pinterest Presents 2026 UK on-demand video · vendor claims · September 2026";

export default function Home(){
 const ref=useRef<HTMLElement>(null); const[a,setA]=useState(0); const[menu,setMenu]=useState(false);
 const progress=useMemo(()=>`${((a+1)/slides.length)*100}%`,[a]);
 useEffect(()=>{const s=ref.current;if(!s)return;const p=Array.from(s.querySelectorAll<HTMLElement>("[data-story-panel]"));const f=()=>{const o=s.getBoundingClientRect().left;setA(p.reduce((b,x,i)=>Math.abs(x.getBoundingClientRect().left-o)<Math.abs(p[b].getBoundingClientRect().left-o)?i:b,0))};s.addEventListener("scroll",f,{passive:true});return()=>s.removeEventListener("scroll",f)},[]);
 const go=(i:number)=>{document.getElementById(slides[Math.max(0,Math.min(slides.length-1,i))][0])?.scrollIntoView({behavior:"smooth",inline:"start"});setMenu(false)};
 return <div className="report-shell"><div className="read-progress"><span style={{width:progress}}/></div><header className="topbar"><button className="noise-mark" onClick={()=>go(0)} aria-label="Go to title"><Image src={asset("noise-logo-black.png")} alt="Noise Media" width={1920} height={830} unoptimized/></button><div className="report-name"><span>Noise ×</span><strong>Pinterest Presents 2026</strong></div><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Open slide menu"><i/><i/><i/></button></header><aside className={`chapter-nav ${menu?"open":""}`}><p>Jump to slide</p><nav>{slides.map((x,i)=><button key={x[0]} className={a===i?"active":""} onClick={()=>go(i)}><span>{String(i+1).padStart(2,"0")}</span>{x[1]}</button>)}</nav></aside><main className="horizontal-story" ref={ref} aria-label="Pinterest Presents 2026 internal event recap">

<S id="title" dark><div className="thank-you-main"><p className="thank-kicker">Internal event recap · 1h 50m on-demand programme</p><h1>Pinterest wants to turn intention into action.</h1><p className="title-period">The full event story: audience, AI, product announcements, brand cases, measurement and trends</p></div><Foot>01 / 22</Foot></S>


<S id="opening"><H n="02" e="The opening scene" t="The show began in a Pinterest-made apartment, then widened into a thesis about the internet." p="The hosts ran through rooms styled from their boards, turning saved ideas into a physical set. It was a playful demonstration of the event's core idea: what happens on Pinterest is supposed to leave the screen."/><div className="editorial-story"><article><span>WHAT HAPPENED</span><p>The opening sketch moved from fashion and home inspiration to products in hand, then handed the stage to CEO Bill Ready. His question was not simply what AI can do, but what people should ask it to do. He described AI as a powerful genie: useful only when the wish is chosen carefully.</p></article><article><span>THE THESIS</span><p>Pinterest's answer was that technology should help people live richer lives offline. The event returned to that position throughout: visual search should help someone name a desire, Assistant should help them work through a complex choice, and advertising should appear while that choice is still open.</p></article></div><Thread>That philosophical opening set up the next question: why does Pinterest think people are ready for a different kind of platform now?</Thread><Src/></S>

<S id="run"><H n="03" e="What the event covered" t="Seven chapters, one commercial argument." p="Pinterest Presents moved from a critique of attention-led social media into a case for visual discovery, then into the tools and evidence intended to prove it can drive performance."/><div className="happens-grid"><Phase l="CONSUMER + PRODUCT" rows={["Bill Ready: Pinterest's real-life mission and platform scale","Claudine Cheever: attention fatigue, Gen Z and offline life","Matt Madrigal + Jett Sissant: visual search, Pinterest Intelligence and Assistant"]}/><Phase l="ADVERTISING" rows={["Lee Brown: three advertiser promises","David Brinker: expert-led creator commerce","Chloe Wicks: Visual Search Ads, Performance Plus, app, CTV, AI tools and formats"]}/><Phase l="PROOF + PRACTICE" rows={["Sephora, Samsung and Levi's brand examples","Measured on incrementality and omnichannel measurement","Sydney Stanback, Netflix and Dove on trends and holiday planning"]}/></div><Src/></S>

<S id="takeaways"><H n="04" e="Executive takeaways" t="The event in one page." p="The programme was part point of view, part product launch: Pinterest explained how it sees the internet changing, then showed the technology and ad products it believes fit that change."/><div className="month-points"><Card n="01" t="The moment matters">Pinterest says it reaches people after inspiration begins but before a brand or product is chosen. That is the core media proposition.</Card><Card n="02" t="AI is the operating layer">Assistant, visual search and Pinterest Intelligence connect personal taste, product understanding and commercial intent.</Card><Card n="03" t="Performance needs proof">Pinterest supported the performance story with selected case studies and an independent measurement discussion about controlled, omnichannel incrementality tests.</Card></div><Call l="How the event connected">The consumer story, AI demonstrations and advertising launches all supported the same claim: Pinterest can influence a choice before a user has named the brand or product.</Call><Src/></S>

<S id="reset"><H n="05" e="Bill Ready · CEO" t="The opening argument: technology should create a reason to go offline." p="Ready framed AI as a choice about outcomes. Pinterest says it is engineering for richer real-world lives rather than maximising time spent."/><div className="story-boxes"><Box l="Mission" v="Real life" p="AI should help people decide, make, buy or do something away from the screen."/><Box l="Product change" v="Visual + shopping" p="Pinterest described itself as fundamentally different from a few years ago: a visual search and shopping engine."/><Box l="Business change" v="Performance" p="The company says it rebuilt lower-funnel capability, moving beyond awareness into measurable action."/><Box l="Brand safety" v="Positive" p="Pinterest positioned positivity and safety as part of the product, not a layer added after reach is bought."/></div><Src/></S>

<S id="culture"><H n="06" e="Claudine Cheever · CMO" t="The cultural story is about attention fatigue, not another feed." p="Cheever argued that people are rejecting experiences designed to keep them watching and are actively looking for prompts to do things in real life."/><div className="detail-grid cols-4"><Metric l="Gen Z sentiment" v="40%" p="reportedly wish social media had never been invented"/><Metric l="Instead of scrolling" v="+350%" p="YoY growth in Gen Z searches for things to do"/><Metric l="Analog interests" v=">2×" p="growth in searches including dumb phones and offline activities"/><Metric l="Examples" v="Hands-on" p="nature, film photography, model cars, pottery and food-making"/></div><Call l="Pinterest's conclusion">The company contrasted intention with attention: it says useful content that leads to an offline action matters more than maximising time spent.</Call><Src/></S>


<S id="turn"><H n="07" e="The first turn in the story" t="Pinterest moved from what people are rejecting to what it says they are looking for." p="After the critique of attention-led feeds, the event reframed Pinterest's long-standing difference as a commercial advantage."/><div className="editorial-story"><article><span>FROM ATTENTION</span><p>Claudine Cheever's section said people miss real life and are searching for activities that restore it. The point was not that screens disappear. It was that a useful digital experience should help someone act, make, try or buy rather than keep them in an endless loop.</p></article><article><span>TO INTENTION</span><p>Bill Ready then supplied the scale and behaviour behind that argument: 640 million monthly users, more than half Gen Z, more than 80 billion monthly searches, and an unusually high share of unbranded queries. Pinterest's pitch is that intention can be valuable before it becomes a named search.</p></article></div><Thread>With the cultural case established, Matt Madrigal took the stage to show how Pinterest tries to turn a vague feeling into a concrete decision.</Thread><Src/></S>

<S id="scale"><H n="08" e="Audience + commercial intent" t="Pinterest says scale now comes with an unusually open decision window." p="The headline numbers describe a large audience whose searches are often commercial but usually do not name a brand."/><div className="detail-grid cols-4"><Metric l="Monthly audience" v="640M" p="people, with 12 consecutive quarters of record users"/><Metric l="Gen Z" v=">50%" p="of the audience; largest and fastest-growing demographic"/><Metric l="Monthly searches" v="80B+" p="the vast majority described as visual"/><Metric l="Open choice" v="96%+" p="of searches described as unbranded; more than half commercial"/></div><Call l="Why Pinterest highlighted this">The figures support its central positioning: people arrive with a commercial or practical intention while their brand and product choices are still open.</Call><Src/></S>

<S id="journey"><H n="09" e="The 'messy middle'" t="The product is built around moving from a feeling to a decision." p="Matt Madrigal described the stretch between wanting something and knowing exactly what it is. Pinterest's job is to keep the user moving without forcing perfect keywords."/><div className="happens-grid"><Phase l="1 · SEE" rows={["A Pin, image or saved idea starts the journey","The system reads objects and how the whole look fits together","Taste and context shape what appears next"]}/><Phase l="2 · REFINE" rows={["Any image can become a new visual search","No keyword is required","Relevant searches can be filtered by skin tone"]}/><Phase l="3 · DECIDE" rows={["Related products and ideas narrow the choice","Assistant supports complex, multi-turn questions","Brands can appear before the user has named one"]}/></div><Src/></S>

<S id="intelligence"><H n="10" e="Pinterest Intelligence" t="Three systems sit underneath the experience." p="Pinterest says its advantage comes from models built for its own use cases and trained around long-running human curation on the platform."/><div className="story-boxes"><Box l="Content + product" v="What it is" p="Understands objects, products and relationships inside an image rather than treating each item in isolation."/><Box l="Taste graph" v="Who it fits" p="Groups aesthetics and preferences so recommendations can reflect a person's style rather than category popularity alone."/><Box l="Interest hierarchy" v="What changes" p="Tracks interests dynamically as a user moves between broad inspiration and specific decisions."/><Box l="Model approach" v="Fit for purpose" p="Pinterest says it post-trains open-source models and builds specialist systems instead of using one off-the-shelf model for every task."/></div><Src/></S>

<S id="assistant"><H n="11" e="Pinterest Assistant" t="Conversation is used when the decision is complex; visuals stay in control." p="The on-stage demo showed a user photographing a real vanity and asking the Assistant to restyle it from a saved mood board."/><div className="happens-grid"><Phase l="INPUT" rows={["A saved item, board or the user's own photo","A short natural-language prompt rather than a detailed brief","Taste context already present in Pinterest"]}/><Phase l="ASSIST" rows={["Multi-turn comparison and refinement","Complete an outfit from one saved piece","Preview a home idea in the user's own space"]}/><Phase l="OUTPUT" rows={["Visual options rather than a text-only answer","Recommendations grounded in personal taste","A path from inspiration towards products and action"]}/></div><Call l="What is genuinely different">The claim is not 'Pinterest has a chatbot'. It is that conversation can operate on a visual history and taste graph that a generic assistant does not have.</Call><Src/></S>


<S id="pivot"><H n="12" e="The event changed gears" t="Once the Assistant demo ended, Pinterest turned the same consumer story into an advertiser story." p="The transition was deliberate: if Pinterest understands an open decision better, a brand can enter before the user has settled on a product."/><div className="editorial-story"><article><span>WHAT STAYED THE SAME</span><p>The language remained visual and personal. Ads were presented as useful additions to discovery rather than interruptions. Expert creators would add credibility; visual search placements would meet a user while they refined a look; automation would use Pinterest's intent signals to optimise delivery.</p></article><article><span>WHAT CHANGED</span><p>The company was more direct than in earlier years about performance. Lee Brown said Pinterest had rebuilt its lower-funnel business and that advertiser clicks had grown fivefold in three years. Chloe Wicks then spent roughly ten minutes announcing the products intended to make that claim tangible.</p></article></div><Thread>The next section unpacked those announcements, beginning with three promises Pinterest says advertisers can hold it to.</Thread><Src/></S>

<S id="promise"><H n="13" e="Lee Brown · Chief Business Officer" t="Pinterest made three promises to advertisers." p="This was the bridge from consumer story to commercial offer."/><div className="month-points"><Card n="01" t="Work harder for results">Build awareness and measurable performance; Pinterest says advertiser clicks have grown 5× in three years.</Card><Card n="02" t="Be welcomed, not dismissed">Ads should complete discovery rather than interrupt it because users have not yet picked the item or brand.</Card><Card n="03" t="Be easier to buy globally">Add buying options, automation and support across more markets, with Performance Plus as the default performance layer.</Card></div><Src/></S>

<S id="creators"><H n="14" e="David Brinker · creators" t="Credibility, not celebrity, is the creator strategy." p="Pinterest argued that the creator economy is moving toward specialists whose recommendations combine inspiration with useful expertise."/><div className="detail-grid cols-3"><Metric l="Trust signal" v="80%+" p="of Pinners reportedly feel Pinterest content is informed by expert opinion"/><Metric l="Who breaks through" v="Experts" p="stylists, chefs, designers and makeup artists: professionals first, creators second"/><Metric l="Commerce" v="Amazon" p="storefront linking, product tagging and automatically applied affiliate links"/></div><Call l="What Pinterest claimed">Expert creators can combine inspiration, demonstration and trust. Pinterest said creator partnerships have produced higher ROAS, sales lift and brand awareness, without giving a universal benchmark.</Call><Src/></S>

<S id="searchads"><H n="15" e="Chloe Wicks · performance products" t="Visual Search Ads put brands inside the refinement moment." p="Coming to beta in all ad-eligible markets, the format creates dedicated placements on search pages and Pin close-ups."/><div className="story-boxes"><Box l="Moment" v="High intent" p="Appears while users are still shaping what they want, not after a precise search term is entered."/><Box l="Creative" v="No net new" p="Pinterest says existing campaign assets can be used."/><Box l="Buying" v="Performance Plus" p="The format is compatible with Pinterest's automated performance suite."/><Box l="Objective" v="Lower funnel" p="Pinterest positions it as traditional search-ad benefits adapted to visual discovery."/></div><Src/></S>

<S id="performance"><H n="16" e="Performance Plus" t="Automation remains the default, but advertisers get more control." p="The update was less about a new campaign type than about steering value, products, audiences and proof."/><div className="happens-grid"><Phase l="STEER THE ALGORITHM" rows={["Acquisition values assign different worth to new customers","Priority Products shifts delivery towards selected product groups","Interest and keyword suggestions guide relevant audiences"]}/><Phase l="TEST + LEARN" rows={["Self-serve A/B testing in Ads Manager across ad-eligible markets","No Pinterest team required to set up the test","Use tests to separate product impact from platform reporting"]}/><Phase l="VENDOR CASE" rows={["Princess Polly: 21× increase in ROAS","CPA reportedly down 70%","Treat as a selected case, not a planning benchmark"]}/></div><Src/></S>

<S id="roadmap"><H n="17" e="Product availability" t="What is live, what is beta and what is still coming." p="The event moved quickly across products and separated global releases from betas, tests and year-end expansion plans."/><div className="happens-grid"><Phase l="LIVE / GLOBAL CLAIMS" rows={["Priority Products (from 15 September) and interest/keyword suggestions","Self-serve A/B tests in ad-eligible markets","Max Width Collections in global markets","Standalone Connected TV campaigns"]}/><Phase l="BETA / EXPANSION" rows={["App Promotion beta; global availability targeted by year end","Business Assistant beta in multiple markets; more countries/languages planned","Premier Spotlight Category Takeover testing in the US; select markets planned"]}/><Phase l="COMING" rows={["Visual Search Ads beta across ad-eligible markets","Pinterest MCP: secure link between outside AI tools and Pinterest data/workflows","CTV can join Spotlight buys; Pinterest claims up to 75% more potential reach"]}/></div><Src/></S>


<S id="proof"><H n="18" e="How Pinterest made its case" t="The final third moved from launches to evidence." p="Pinterest did not rely on one kind of proof. It mixed selected advertiser results, a live brand panel, an independent measurement discussion and trend-led creative examples."/><div className="editorial-story"><article><span>THE CASE STUDIES</span><p>Sephora supplied a retail and local-inventory story. Samsung showed a cultural partnership carrying a product from awareness into mid-funnel action. Levi's explained how search behaviour can help an established brand stretch from a famous product into a broader style proposition.</p></article><article><span>THE MEASUREMENT CHECK</span><p>Measured's Trevor Testwuide complicated the simple ROAS story. He argued that last-touch reporting is useful for optimisation but cannot answer causality, especially when customers transact across ecommerce, stores, social commerce and retailers. His recommendation was repeated experimentation, not one decisive platform read.</p></article></div><Thread>The event closed by looking forward: first through Pinterest Predicts and holiday mindsets, then through four summary claims about audience, visual discovery, performance and positivity.</Thread><Src/></S>

<S id="sephora"><H n="19" e="Brand case · Sephora" t="A full-funnel beauty example anchored in local inventory." p="Megan Black, Sephora's SVP of Digital Marketing and Media, described Pinterest as a place where beauty shoppers move through dreaming, deciding and doing."/><div className="story-boxes"><Box l="Test" v="Local inventory" p="Sephora said it was the first beauty retailer to test Pinterest local inventory ads."/><Box l="Return" v="+50%" p="higher ROAS reported from the testing."/><Box l="Efficiency" v="+25%" p="more efficient reach among high-intent beauty shoppers."/><Box l="Learning" v="Full funnel" p="Sephora said upper- and lower-funnel activity perform better when run together."/></div><Call l="What the example showed">Sephora used Pinterest across dreaming, deciding and doing, linking inspiration to nearby inventory and conversion. The lifts are Sephora/Pinterest event claims.</Call><Src/></S>

<S id="brands"><H n="20" e="Brand panel · Samsung + Levi's" t="Both brands use Pinterest to turn broad awareness into a more specific choice." p="Christina Brandaberry hosted Noelle Perez of Samsung and Ann Cambria of Levi's on cultural relevance, visual storytelling and commercial impact."/><div className="happens-grid"><Phase l="SAMSUNG" rows={["Goal: turn brand preference into Galaxy switching and show why product innovation matters","Foldable × Spider-Man work integrated the phone naturally into a cultural moment","Reported 5×+ industry benchmark on mid-funnel impact"]}/><Phase l="LEVI'S" rows={["Goal: move beyond denim awareness into head-to-toe dressing, especially with women","Uses search behaviour to see which styles are gaining interest","Pinterest is used to translate brand-produced fashion content into discovery and consideration"]}/><Phase l="SHARED LESSON" rows={["Start with a real consumer or cultural moment","Make the product role visible, not bolted on","Judge success beyond reach: preference, consideration and action"]}/></div><Src/></S>

<S id="measurement"><H n="21" e="Measured · Trevor Testwuide" t="Last-touch reporting is an optimisation tool, not the complete answer." p="The measurement discussion was the most useful operating guidance in the event: understand causality across every place the customer can transact."/><div className="story-boxes"><Box l="Method" v="Test/control" p="Experiments identify incremental contribution rather than assigning all credit to the last observed action."/><Box l="Scope" v="Omnichannel" p="One test can read across ecommerce, stores, social commerce and third-party retail KPIs."/><Box l="Evidence" v="70 tests" p="Measured independently reviewed recent Pinterest incrementality tests across its clients."/><Box l="Gap" v="2–4×" p="For brands where Pinterest worked, Measured said incremental outcomes could be materially stronger than last-touch reporting suggested."/></div><Call l="Measured's advice on stage">Bring stakeholders together, run a 2–3 test sequence, audit each result, tune the account and retest. Trevor Testwuide said one experiment is not a permanent verdict on a channel.</Call><Src/></S>

<S id="trends"><H n="22" e="Sydney Stanback · trends + holiday" t="Searches and saves are presented as an early read on culture." p="Pinterest says its visual intent data can help brands spot an emerging aesthetic before it becomes obvious elsewhere."/><div className="happens-grid"><Phase l="PINTEREST PREDICTS" rows={["Pinterest says 88% of its predictions came true over six years","Netflix Australia used the Opera Aesthetic trend for Bridgerton","Trend-led creative reportedly drove stronger awareness lift than creative without the Predicts badge"]}/><Phase l="HOLIDAY MINDSET" rows={["People want meaning, memories, personal touches and a softer feel","Four themes included small expressive extras ('the trinket effect')","Pinterest presented trends as inputs to creative and merchandising, not decorative labels"]}/><Phase l="DOVE" rows={["Real Beauty DNA linked Dove's positivity platform to Pinterest","The next chapter used Glitchy Glam to resist clone culture","The example connected a platform trend to an existing brand belief"]}/></div><Src/></S>

</main><div className="slide-controls" aria-label="Deck navigation"><button aria-label="Previous panel" onClick={()=>go(a-1)} disabled={a===0}>← PREVIOUS</button><div><span>{slides[a][1]}</span><strong>{String(a+1).padStart(2,"0")} / {slides.length}</strong></div><button aria-label="Next panel" onClick={()=>go(a+1)} disabled={a===slides.length-1}>NEXT →</button></div></div>}

function S({id,children,dark=false}:{id:string;children:React.ReactNode;dark?:boolean}){return <section id={id} data-story-panel className={`story-panel ${dark?"title-panel thank-you-chapter":"light"}`}>{children}</section>}
function H({n,e,t,p}:{n:string;e:string;t:string;p:string}){return <header className="chapter-header insight-header"><div className="section-number">{n}</div><div><span className="eyebrow">{e}</span><h2>{t}</h2></div><p>{p}</p></header>}
function Card({n,t,children}:{n:string;t:string;children:React.ReactNode}){return <article><span>{n}</span><h3>{t}</h3><p>{children}</p></article>}
function Box({l,v,p}:{l:string;v:string;p:string}){return <article><span>{l}</span><strong>{v}</strong><p>{p}</p></article>}
function Metric({l,v,p}:{l:string;v:string;p:string}){return <article><span>{l}</span><strong>{v}</strong><b>{p}</b></article>}
function Phase({l,rows}:{l:string;rows:string[]}){return <article><span>{l}</span><ul>{rows.map(x=><li key={x}>{x}</li>)}</ul></article>}
function Thread({children}:{children:React.ReactNode}){return <div className="story-thread"><span>AND THEN</span><p>{children}</p></div>}
function Call({l,children}:{l:string;children:React.ReactNode}){return <div className="takeaway-bar"><span>{l}</span><p>{children}</p></div>}
function Src(){return <small style={{display:"block",marginTop:8,color:"#777",fontSize:10}}>{source}</small>}
function Foot({children}:{children:React.ReactNode}){return <div className="thank-foot"><span>Noise internal · vendor claims labelled</span><span>{children}</span></div>}
