"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
const base=process.env.NEXT_PUBLIC_REPORT_BASE_PATH??""; const asset=(x:string)=>`${base}/${x}`;
const slides=[["title","Title"],["recap","Event recap"],["position","Positioning"],["audience","Audience"],["product","Product"],["ads","Ad products"],["evidence","Evidence"],["measurement","Measurement"],["signals","Signals"],["next","Noise next steps"]] as const;
const source="Pinterest event claims · September 2026 · internal recap";
export default function Home(){const ref=useRef<HTMLElement>(null);const[a,setA]=useState(0);const[menu,setMenu]=useState(false);const progress=useMemo(()=>`${((a+1)/slides.length)*100}%`,[a]);useEffect(()=>{const s=ref.current;if(!s)return;const p=Array.from(s.querySelectorAll<HTMLElement>("[data-story-panel]"));const f=()=>{const o=s.getBoundingClientRect().left;setA(p.reduce((b,x,i)=>Math.abs(x.getBoundingClientRect().left-o)<Math.abs(p[b].getBoundingClientRect().left-o)?i:b,0))};s.addEventListener("scroll",f,{passive:true});return()=>s.removeEventListener("scroll",f)},[]);const go=(i:number)=>{document.getElementById(slides[Math.max(0,Math.min(9,i))][0])?.scrollIntoView({behavior:"smooth",inline:"start"});setMenu(false)};return <div className="report-shell"><div className="read-progress"><span style={{width:progress}}/></div><header className="topbar"><button className="noise-mark" onClick={()=>go(0)}><Image src={asset("noise-logo-black.png")} alt="Noise Media" width={1920} height={830} unoptimized/></button><div className="report-name"><span>Noise ×</span><strong>Pinterest event recap</strong></div><button className="menu-toggle" onClick={()=>setMenu(!menu)}><i/><i/><i/></button></header><aside className={`chapter-nav ${menu?"open":""}`}><p>Jump to slide</p><nav>{slides.map((x,i)=><button key={x[0]} className={a===i?"active":""} onClick={()=>go(i)}><span>{String(i+1).padStart(2,"0")}</span>{x[1]}</button>)}</nav></aside><main className="horizontal-story" ref={ref} aria-label="Pinterest event recap">
<S id="title" dark><div className="thank-you-main"><p className="thank-kicker">Internal event recap · September 2026</p><h1>Pinterest is pitching intent before decision.</h1><p className="title-period">What changed · what Pinterest claims · what Noise should test</p></div><Foot>01 / 10</Foot></S>
<S id="recap"><H n="02" e="Executive recap" t="Three things matter for Noise." p="Pinterest's event pitch joins a distinct user moment, a more automated ad stack and a different measurement standard."/><div className="month-points"><Card n="01" t="Not another social feed">Pinterest says it sits between inspiration and purchase: 96% of searches are unbranded and more than half are commercial.</Card><Card n="02" t="Visual AI is the product">Assistant, visual search and product understanding aim to shorten complex discovery without turning the platform into a chatbot.</Card><Card n="03" t="The test must be incremental">Pinterest argues last-click misses its value. Any Noise recommendation needs a test/control design, not platform ROAS alone.</Card></div><Call l="Internal implication">Treat Pinterest as a discovery-to-commerce test environment, not a default paid-social budget line.</Call><Src/></S>
<S id="position"><H n="03" e="Platform positioning" t="Pinterest wants to own the moment before a brand is chosen." p="The claimed advantage is not time spent. It is commercial intent while the decision is still open."/><div className="story-boxes"><Box l="Search behaviour" v="96%" p="of searches are unbranded, according to Pinterest."/><Box l="Commercial signal" v=">50%" p="of searches are commercial, according to Pinterest."/><Box l="Experience" v="Visual" p="Every image can become a new search start, without keywords."/><Box l="Noise meaning" v="Earlier" p="A chance to shape the shortlist before search and retargeting harvest demand."/></div><Src/></S>
<S id="audience"><H n="04" e="Audience and growth" t="Gen Z growth is tied to an anti-scroll mood." p="Pinterest framed growth as a response to attention fatigue, not evidence that people want another feed."/><div className="detail-grid cols-4"><Metric l="Monthly users" v="640M" p="12 straight quarters of record growth"/><Metric l="Gen Z share" v=">50%" p="Fastest-growing demographic"/><Metric l="Instead of scrolling" v="+350%" p="Gen Z search growth YoY"/><Metric l="Analog activities" v="2×+" p="Film photography, pottery, dumb phones"/></div><Call l="Tension to use">40% of Gen Z reportedly wish social media had never been invented. Creative should help people do something, not ask them to keep watching.</Call><Src/></S>
<S id="product"><H n="05" e="Product mechanism" t="Visual when visuals matter; conversational when the task gets complex." p="Pinterest's product story links the user's own images to a live model of products, tastes and changing interests."/><div className="story-boxes"><Box l="Pinterest Assistant" v="Talk + see" p="Multi-turn outfit styling and room restyling using a user's own photos."/><Box l="Visual search" v="Any image" p="No keyword required; skin-tone filtering is available for relevant searches."/><Box l="Pinterest Intelligence" v="3 signals" p="Content/product understanding, taste clusters and a dynamic interest hierarchy."/><Box l="Claimed moat" v="100Bs" p="Hundreds of billions of real-time connections make visual understanding harder to copy."/></div><Src/></S>
<S id="ads"><H n="06" e="Ad products" t="The stack is moving from inspiration into automated performance." p="Availability matters. Separate products we can use now from betas and announced launches."/><div className="happens-grid"><Phase l="LIVE NOW" rows={["Performance Plus: acquisition values + priority products","Global interest and keyword targeting","Self-serve A/B tests","Visual Search Ads; no new creative claimed","Collage Ads + Max Width Collections","Connected TV standalone or with Spotlight Fives"]}/><Phase l="BETA / TESTING" rows={["App Promotion beta","Business Assistant in multiple markets","Premier Spotlight Category Takeover in US","Pinterest MCP entering beta soon"]}/><Phase l="CLAIMED PERFORMANCE SHIFT" rows={["Advertiser clicks up 5× in three years","Connected TV adds up to 75% reach","App Promotion due globally by year end"]}/></div><Src/></S>
<S id="evidence"><H n="07" e="Brand case studies" t="The proof is promising, but it is vendor-selected." p="Use these as hypotheses for where Pinterest can work, not as expected outcomes for Noise clients."/><div className="detail-grid cols-4"><Metric l="Sephora" v="+50% ROAS" p="Local inventory ads; 25% more efficient reach"/><Metric l="Princess Polly" v="21× ROAS" p="Performance Plus; CPA reportedly down 70%"/><Metric l="Samsung" v="5×" p="Mid-funnel benchmark; Circle to Search completion 25%"/><Metric l="Levi's" v="Outperformed" p="Paid Pinterest reportedly beat other paid social"/></div><Call l="Decision use">The cases point to retail, visual products and mid-funnel launches. They do not remove the need for a client-specific incrementality test.</Call><Src/></S>
<S id="measurement"><H n="08" e="Measurement" t="Pinterest's strongest argument is that last click undercounts discovery." p="Measured's event case was for causality: test/control, audited reads and omnichannel outcomes."/><div className="story-boxes"><Box l="Problem" v="Last touch" p="Still used by brands spending $50–100M+, despite misattributing earlier influence."/><Box l="Method" v="2–3 tests" p="Run a sequence, audit each result and involve all stakeholders."/><Box l="Independent review" v="70 tests" p="Measured reviewed Pinterest incrementality tests."/><Box l="Claimed gap" v="2–4×" p="Where Pinterest works, incremental results may exceed last-touch reporting by this amount."/></div><Call l="Gate">No scale recommendation until a test proves incremental value across ecommerce and offline outcomes.</Call><Src/></S>
<S id="signals"><H n="09" e="Creators and trends" t="Pinterest may be most useful where expertise and aesthetics guide a choice." p="Two adjacent signals could make the channel distinctive: trusted experts and trend-led planning."/><div className="detail-grid cols-3"><Metric l="Expert influence" v="80%+" p="Pinners reportedly say content is informed by expert opinion"/><Metric l="Pinterest Predicts" v="88%" p="of predictions reportedly came true over six years"/><Metric l="Commerce link" v="Amazon" p="Creators can link storefronts and apply affiliate links automatically"/></div><Call l="Holiday 2026">Pinterest's theme is meaning, memories, personal touches and a softer feel. Netflix and Dove examples show trends becoming creative inputs, not only targeting signals.</Call><Src/></S>
<S id="next"><H n="10" e="Noise view" t="Test the hypothesis before we sell the channel." p="One sequence, with owners and gates. Missing client, budget and market choices remain intentionally open."/><div className="happens-grid"><Phase l="NOW · STRATEGY" rows={["Owner: Paid Media · shortlist visual-commerce clients","Owner: Strategy · define Pinterest's job versus Meta and Search","Gate: clear incremental outcome + eligible market"]}/><Phase l="NEXT · TEST" rows={["Owner: Paid + Analytics · design 2–3 test sequence","Owner: Creative · adapt existing product assets first","Gate: holdout/control agreed before launch"]}/><Phase l="LATER · SCALE" rows={["Owner: Analytics · audit ecommerce + offline impact","Owner: Client lead · compare incremental return across channels","Gate: scale only if causality and lead quality hold"]}/></div><Src/></S>
</main><div className="slide-controls" aria-label="Deck navigation"><button onClick={()=>go(a-1)} disabled={a===0}>← PREVIOUS</button><div><span>{slides[a][1]}</span><strong>{String(a+1).padStart(2,"0")} / 10</strong></div><button onClick={()=>go(a+1)} disabled={a===9}>NEXT →</button></div></div>}
function S({id,children,dark=false}:{id:string;children:React.ReactNode;dark?:boolean}){return <section id={id} data-story-panel className={`story-panel ${dark?"title-panel thank-you-chapter":"light"}`}>{children}</section>};
function H({n,e,t,p}:{n:string;e:string;t:string;p:string}){return <header className="chapter-header insight-header"><div className="section-number">{n}</div><div><span className="eyebrow">{e}</span><h2>{t}</h2></div><p>{p}</p></header>};
function Card({n,t,children}:{n:string;t:string;children:React.ReactNode}){return <article><span>{n}</span><h3>{t}</h3><p>{children}</p></article>};
function Box({l,v,p}:{l:string;v:string;p:string}){return <article><span>{l}</span><strong>{v}</strong><p>{p}</p></article>};
function Metric({l,v,p}:{l:string;v:string;p:string}){return <article><span>{l}</span><strong>{v}</strong><b>{p}</b></article>};
function Phase({l,rows}:{l:string;rows:string[]}){return <article><span>{l}</span><ul>{rows.map(x=><li key={x}>{x}</li>)}</ul></article>};
function Call({l,children}:{l:string;children:React.ReactNode}){return <div className="takeaway-bar"><span>{l}</span><p>{children}</p></div>};
function Src(){return <small style={{display:"block",marginTop:8,color:"#777",fontSize:10}}>{source}</small>};
function Foot({children}:{children:React.ReactNode}){return <div className="thank-foot"><span>Noise internal · vendor claims labelled</span><span>{children}</span></div>};
